instanceSpace: springfield_sap
sourceName: SAP Springfield S/4HANA
rawDatabase: sap_s4hana # can also contain location, for example sap_springfield_s4hana
source: sap_s4hana # can also contain location, for example sap_springfield_s4hana
transformationServicePrincipalGroupObjectId: <not set>
workflow: sap_s4hana_population # can also contain location sap_springfield_s4hana_population
dataset: sap_s4hana_transformations # can also contain location sap_springfield_s4hana_transformations
schemaSpace: cdf_cdm
