instanceSpace: sp_springfield_sap
sourceName: SAP Springfield S/4HANA
rawDb: sap_springfield_staging
sourceId: sap_springfield_s4hana
transformationServicePrincipalGroupObjectId: <not set>
workflow: sap_springfield_s4hana_population
dataset: ds_sap_springfield_s4hana_transformations
