externalId: '{{ annotatorJob }}'
config:
  parameters:
    autoApprovalThreshold: 0.85
    autoRejectThreshold: 0.25
    featureType: "bigram"
  sourceSystem:
    space: {{ annotationSpace }}
    externalId: {{ contextualizationId }}
  data:
    annotationSpace: '{{ annotationSpace }}'
    instanceSpaces:
      {{ instanceSpaces }}
    state:
      rawDatabase: {{ rawStateDatabase }}
      rawTable: {{ rawStateTable }}
    matchingJobs:
      job1:
        sourceView:
          space: {{ schemaSpace }}
          externalId: CogniteTimeSeries
          version: v1
          properties:
            - name
        targetViews:
          - space: {{ schemaSpace }}
            externalId: CogniteEquipment
            version: v1
            properties:
              - name
          - space: {{ schemaSpace }}
            externalId: CogniteAsset
            version: v1
            properties:
              - name
