sourceName: Springfield Sharepoint
sourceId: springfield_sharepoint
rawDatabase: files_metadata_staging # can also contain location, for example files_metadata_springfield_staging
transformationServicePrincipalGroupObjectId: <not set>
dataset: files_metadata_transformations # can also contain location, for example files_metadata_springfield_transformations
schemaSpace: cdf_cdm
instanceSpace: files_metadata_instances
