space: cdf_cdm
externalId: CogniteCore
name: Cognite core data model
description: Cognite core data model
version: v1
views:
- space: cdf_cdm
  externalId: CogniteDescribable
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteSourceable
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteSourceSystem
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteSchedulable
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteVisualizable
  version: v1
  type: view
- space: cdf_cdm
  externalId: Cognite3DTransformation
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteCubeMap
  version: v1
  type: view
- space: cdf_cdm
  externalId: Cognite3DObject
  version: v1
  type: view
- space: cdf_cdm
  externalId: Cognite3DModel
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteCADModel
  version: v1
  type: view
- space: cdf_cdm
  externalId: Cognite3DRevision
  version: v1
  type: view
- space: cdf_cdm
  externalId: CognitePointCloudModel
  version: v1
  type: view
- space: cdf_cdm
  externalId: Cognite360ImageModel
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteCADRevision
  version: v1
  type: view
- space: cdf_cdm
  externalId: CognitePointCloudRevision
  version: v1
  type: view
- space: cdf_cdm
  externalId: Cognite360ImageCollection
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteCADNode
  version: v1
  type: view
- space: cdf_cdm
  externalId: CognitePointCloudVolume
  version: v1
  type: view
- space: cdf_cdm
  externalId: Cognite360Image
  version: v1
  type: view
- space: cdf_cdm
  externalId: Cognite360ImageStation
  version: v1
  type: view
- space: cdf_cdm
  externalId: Cognite360ImageAnnotation
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteAsset
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteAssetClass
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteAssetType
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteEquipment
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteEquipmentType
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteFile
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteFileCategory
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteActivity
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteTimeSeries
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteAnnotation
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteDiagramAnnotation
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteUnit
  version: v1
  type: view
