---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    hooks:
      - id: ruff
        args:
          - --fix
          - --exit-non-zero-on-fix
          - --ignore=E731,E501,W605,T201,UP007
            # See https://beta.ruff.rs/docs/rules for an overview of ruff rules
          - --select=E,W,F,I,T,RUF,TID,UP
          - --fixable=E,W,F,I,T,RUF,TID,UP
          - --target-version=py39
      - id: ruff-format
    rev: v0.5.0

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: debug-statements
      - id: check-docstring-first
      # Tests with rich print tables++ will fail if we remove trailing whitespaces
      #- id: trailing-whitespace

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
    - id: markdownlint

# Mypy must be run in the local system environment, not in the pre-commit environment.
  - hooks:
    - id: mypy
      name: mypy
      entry: mypy cognite_toolkit/ --config-file pyproject.toml
      files: ^.*.(py|pyi)$
      language: system
      pass_filenames: false
    repo: local
