[cdf]
default_organization_dir = "cognite_toolkit"
#default_env = "dev"

[alpha_flags]
graphql = true
import-cmd = true
module-repeat = true
dump-extended = true
populate = true
strict-validation = true
# Setting this to true wil change all snapshots for WorkflowTriggers/FunctionSchedules.
# For simplicity, (avoid keeping track of two sets of snapshots), we keep this to false in development.
credentials-hash = false

[plugins]
run = true
purge = true
dump = true

[[my_resource_folders]]
[scene]
space = "scene"
externalId = "scene_data_model"
version = "1"
type = "datamodel"

[modules]
# This is the version of the modules. It should not be changed manually.
# It will be updated by the 'cdf modules upgrade' command.
version = "0.4.9"
