dataset: contextualisation_transformations
instanceSpace: springfield_instances
schemaSpace: cdf_cdm
groupSourceId: <not set>
transformationClientId: ${TRANSFORMATION_CLIENT_ID}
transformationClientSecret: ${TRANSFORMATION_CLIENT_SECRET}
transformationTokenUri: ${IDP_TOKEN_URL}
transformationCdfProjectName: ${CDF_PROJECT}
transformationAudience: ${CDF_URL}
transformationScope: ${IDP_SCOPES}
