instanceSpace: springfield_instances
schemaSpace: cdf_cdm
transformationServicePrincipalGroupObjectId: <not set>
dataset: contextualisation_transformations
transformationClientId: ${TRANSFORMATION_CLIENT_ID}
transformationClientSecret: ${TRANSFORMATION_CLIENT_SECRET}
transformationTokenUri: ${IDP_TOKEN_URL}
transformationCdfProjectName: ${CDF_PROJECT}
transformationAudience: ${CDF_URL}
transformationScope: ${IDP_SCOPES}