autoCreateDirectRelations: true
skipOnVersionConflict: false
replace: true
nodes:
- space: cognite_app_data # should we have a separate space to avoid users overwriting config?
  externalId: '{{location}}_app_config'
  sources:
  - source:
      space: cdf_infield
      externalId: InFieldLocationConfig
      version: '1'
      type: view
    properties:
      rootLocationExternalId: '{{location_external_id}}' #ads location
      classicAssetExternalId: '{{location_root_asset_external_id}}'
      appInstanceSpace: sp_infield_{{location}}_app_data
      # sourceInstanceSpace: sp_asset_{{location}}_source
      accessManagement: 
        templateAdmins:
          - gp_infield_{{location}}_template_admins
        checklistAdmins:
          - gp_infield_{{location}}_checklist_admins