[module]
title = "SAP Source System Asset/Equipment Metadata"

[packages]
tags = [
    "sourcesystem",
    "quickstart",
]

[dependencies]
modules = []

[[data]]
repo = "https://github.com/cognitedata/toolkit-data.git"
source = "data/publicdata/assets.Table.csv"
destination = "raw/dump.Table.csv"
