sourceName: SAP Springfield S/4HANA
sourceId: sap_springfield_s4hana
maintenanceOrderTransformationExternalId: sap_maintenance_orders_springfield_s4hana
operationTransformationExternalId: sap_operations_springfield_s4hana
operationToMaintenanceOrderTransformationExternalId: sap_operation_to_maintenance_order_springfield_s4hana
dataset: sap_s4hana_transformations # can also contain location sap_springfield_s4hana_transformations
rawDatabase: sap_s4hana # can also contain location, for example sap_springfield_s4hana
groupSourceId: <not set>
schemaSpace: cdf_idm
instanceSpace: springfield_instances

workflow: sap_s4hana_population_events # can also contain location sap_springfield_s4hana_population
transformationClientId: ${SAP_SPRINGFIELD_S4HANA_CLIENT_ID}
transformationClientSecret: ${SAP_SPRINGFIELD_S4HANA_CLIENT_SECRET}
transformationTokenUri: ${IDP_TOKEN_URL}
transformationCdfProjectName: ${CDF_PROJECT}
transformationAudience: ${CDF_URL}
transformationScope: ${IDP_SCOPES}
