environment:
  name: prod
  project: <my-project-prod>
  type: prod
  selected:
  - modules/

variables:
  modules:
    industrial_tools:
      search:
        location: springfield
        locationName: Springfield
        instanceSpace: springfield_instances
