externalId: springfield
name: Springfield
description: 'The Springfield site'
dataModels:
  - space: cdf_cdm_experimental
    externalId: core_data_model
    version: v1
instanceSpaces:
  - space: sp_sap_springfield_data
views: []