contextualizationId: p_and_id_parser
contextualizationName: P&ID Parser
functionServicePrincipalGroupObjectId: <not_set>
dataset: ds_p_and_id_parser
schemaSpace: cdf_cdm
annotationSpace: sp_p_and_id_parser
instanceSpaces:
  - files_metadata_instances
  - springfield_sap
functionClientId: ${P_AND_ID_PARSER_CLIENT_ID}
functionClientSecret: ${P_AND_ID_PARSER_CLIENT_SECRET}
rawDatabase: contextualizationState
rawTable: diagramParsing
workflow: p_and_id_parser