externalId: '{{ directRelationJob }}'
config:
  state:
    rawDatabase: {{ rawDatabase }}
    rawTable: {{ rawTable }}
  data:
    annotationSpace: '{{ annotationSpace }}'
    directRelationMappings:
      - startNode:
          space: {{ schemaSpace }}
          externalId: CogniteFile
          version: v1
          directRelationProperty: assets
        endNode:
          space: {{ schemaSpace }}
          externalId: CogniteAsset
          version: v1
      - startNode:
          type: view
          space: {{ schemaSpace }}
          externalId: CogniteFile
          version: v1
        endNode:
          type: viewProperty
          space: {{ schemaSpace }}
          externalId: CogniteEquipment
          version: v1
          directRelationProperty: files
# Unique Entity Source externalId is assumed in sync call