externalId: '{{ directRelationJob }}'
config:
  state:
    rawDatabase: {{ rawDatabase }}
    rawTable: {{ rawTable }}
  data:
    annotationSpace: '{{ annotationSpace }}'
    instanceSpaces:
      {{ instanceSpaces }}
    directRelationMappings:
      - fileSource:
          space: {{ schemaSpace }}
          externalId: CogniteFile
          version: v1
          directRelationProperty: assets
        entitySource:
          space: {{ schemaSpace }}
          externalId: CogniteAsset
          version: v1
      - fileSource:
          type: view
          space: {{ schemaSpace }}
          externalId: CogniteFile
          version: v1
        entitySource:
          type: viewProperty
          space: {{ schemaSpace }}
          externalId: CogniteEquipment
          version: v1
          directRelationProperty: files
# Unique Entity Source externalId is assumed in sync call