environment:
  name: dev
  project: <my-project-dev>
  type: dev
  selected:
  - inrobot

variables:
  inrobot:
    first_root_asset_external_id: <change_me>
    first_location: <change_me>
    robot_1_dataset_ext_id: ds_robot_1
    cdf_inrobot_location:
      inrobot_admin_first_location_source_id: <change_me>
      inrobot_users_first_location_source_id: <change_me>
      robot_1_first_location_source_id: <change_me>
      three_d_model_name: <change_me>
      three_d_type: <change_me>
      three_d_model_id: <change_me>
      three_d_revision_id: <change_me>

    cdf_inrobot_common:
      run_function_user_group_source_id: <change_me>
      run_function_client_id: <change_me>
      run_function_secret: <change_me>
