name: Deploy modules to demo project
on:
  push:
    branches:
      - main
env:
  PYTHON_VERSION: '3.9'
jobs:
  build-modules:
    runs-on: ubuntu-latest
    environment: dev
    env:
        CDF_CLUSTER: ${{ secrets.CDF_CLUSTER }}
        CDF_PROJECT: ${{ secrets.CDF_PROJECT }}
        IDP_CLIENT_ID: ${{ secrets.IDP_CLIENT_ID }}
        IDP_CLIENT_SECRET: ${{ secrets.IDP_CLIENT_SECRET }}
        IDP_TOKEN_URL: ${{ secrets.IDP_TOKEN_URL }}
    name: Loadmaster
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: snok/install-poetry@v1
        with:
          version: 1.6.1
          virtualenvs-create: false
      - name: Install dependencies and build the package
        run: |
          poetry install
          poetry build
      - name: Install cdf-tk
        run: pip install .
      - name: Initialize project
        run: cdf modules init demo_project --clean --all
      - name: "Pre-processing for demo environment"
        run: python ./demo/preproc.py
      - name: "Not collect metrics"
        run: cdf collect opt-out
      - name: "Build the templates"
        run: cdf-tk build --build-dir=./build --env=demo ./demo_project
      # be careful, this works as promised
#      - name: "Delete existing resources including data"
#        run: |
#          cdf-tk clean --env=demo ./build --include data_models
      - name: "Verify and create access rights"
        run: cdf-tk auth verify
      - name: "Allow some time for data modeling to finish syncing of deletions"
        run: |
          sleep 30
      - name: "Deploy the templates"
        run: |
          cdf-tk deploy --drop --env=demo ./build
      - name: "Run transformations and other post-processing"
        run: |
          poetry run python ./demo/postproc.py
