name: Release pypi package
on:
  push:
    branches:
      - release
env:
  PYTHON_VERSION: '3.11'
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: CD
    # This causes issues when CDF is down.
    #needs: [lint, test, build]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: snok/install-poetry@v1
        with:
          version: 1.6.1
          virtualenvs-create: false
      - name: Install dependencies
        run: poetry install
      - name: Build package
        run: poetry build
      - name: Release to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload --verbose dist/*
