sourceName: Springfield AVEVA PI
sourceId: springfield_aveva_pi # can also contain location, for example sap_springfield_s4hana
timeseriesTransformationExternalId: pi_timeseries_springfield_aveva_pi
dataset: aveva_pi_population # can also contain location aveva_pi_springfield_population
rawDatabase: aveva_pi_staging # can also contain location, for example aveva_pi_springfield_staging
schemaSpace: cdf_cdm
instanceSpace: springfield_instances

groupSourceId: <not set>
workflow: aveva_pi_population # can also contain location aveva_pi_springfield_population
workflowClientId: ${AVEVA_PI_SPRINGFIELD_CLIENT_ID}
workflowClientSecret: ${AVEVA_PI_SPRINGFIELD_CLIENT_SECRET}
