[module]
title = "OSIsoft/AVEVA PI Data Source"
is_selected_by_default = false

[packages]
tags = [
    "sourcesystem",
    "quickstart",
]

[dependencies]
modules = []

[[data]]
url = "https://github.com/cognitedata/toolkit-data.git"
source = "data/publicdata/cdf_pi.Table.csv"
destination = "raw/timeseries.Table.csv"
